name: devops test

on:
  push:
    branches: [ main ]
    
jobs:
  deploy:
    name: ansible test
    runs-on: ubuntu-latest

    steps:
    - name: get code from github
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.REMOTE_PORT }}
        script: |
          sudo rm -rf frontend
          sudo git clone https://github.com/ddarahakit2023/frontend
          sudo cd frontend
          sudo npm i
          sudo npm run build
          sudo docker build --tag ddarahakit2023/frontend:latest .
          sudo docker login -u ddarahakit2023 -p Dkagh1234!
          sudo docker push ddarahakit2023/frontend:latest
          docker-compose -f web.yml pull
          docker-compose -f web.yml up --force-recreate