name: frontend devops

on:
  push:
    branches: [ main ]


jobs:
  deploy:
    name: frontend test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
    - run: npm run build
    
    - name: 테스트 결과를 PR에 코멘트로 등록합니다
      uses: EnricoMi/publish-unit-test-result-action@v1
      with:
        files: 'test-results/TEST-*.xml'